/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.awt.Color;

/**
 *
 * @author AAYUSH
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchrecord = new javax.swing.JButton();
        addfees = new javax.swing.JButton();
        editcourse = new javax.swing.JButton();
        viewcourse = new javax.swing.JButton();
        viewrecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 3, 48)); // NOI18N
        jLabel1.setText("PAYEASE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchrecord.setFont(new java.awt.Font("Palatino Linotype", 0, 16)); // NOI18N
        searchrecord.setText("SEARCH RECORD");
        searchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchrecordMouseExited(evt);
            }
        });
        searchrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchrecordActionPerformed(evt);
            }
        });

        addfees.setFont(new java.awt.Font("Palatino Linotype", 0, 16)); // NOI18N
        addfees.setText("ADD FEES");
        addfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addfeesMouseExited(evt);
            }
        });
        addfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfeesActionPerformed(evt);
            }
        });

        editcourse.setFont(new java.awt.Font("Palatino Linotype", 0, 16)); // NOI18N
        editcourse.setText("EDIT RECORD");
        editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcourseMouseExited(evt);
            }
        });
        editcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcourseActionPerformed(evt);
            }
        });

        viewcourse.setFont(new java.awt.Font("Palatino Linotype", 0, 16)); // NOI18N
        viewcourse.setText("VIEW COURSE");
        viewcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewcourseMouseExited(evt);
            }
        });
        viewcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcourseActionPerformed(evt);
            }
        });

        viewrecord.setFont(new java.awt.Font("Palatino Linotype", 0, 16)); // NOI18N
        viewrecord.setText("VIEW RECORD");
        viewrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecordMouseExited(evt);
            }
        });
        viewrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(viewcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(editcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(addfees, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(addfees, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchrecordMouseEntered
        Color c1=new Color(16);
        searchrecord.setBackground(c1);
    }//GEN-LAST:event_searchrecordMouseEntered

    private void searchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchrecordMouseExited
         Color c1=new Color(255,255,255);
        searchrecord.setBackground(c1);
    }//GEN-LAST:event_searchrecordMouseExited

    private void addfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfeesMouseEntered
         Color c1=new Color(16);
        addfees.setBackground(c1);
    }//GEN-LAST:event_addfeesMouseEntered

    private void addfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfeesMouseExited
        Color c1=new Color(255,255,255);
        addfees.setBackground(c1);
    }//GEN-LAST:event_addfeesMouseExited

    private void editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseEntered
         Color c1=new Color(16);
        editcourse.setBackground(c1);
    }//GEN-LAST:event_editcourseMouseEntered

    private void editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseExited
        Color c1=new Color(255,255,255);
        editcourse.setBackground(c1);
    }//GEN-LAST:event_editcourseMouseExited

    private void addfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfeesActionPerformed
addfees a1=new addfees();
a1.show();
this.dispose();
    }//GEN-LAST:event_addfeesActionPerformed

    private void viewcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewcourseMouseEntered
        Color c1=new Color(16);
        viewcourse.setBackground(c1);
    }//GEN-LAST:event_viewcourseMouseEntered

    private void viewcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewcourseMouseExited
        Color c1=new Color(255,255,255);
        viewcourse.setBackground(c1);
    }//GEN-LAST:event_viewcourseMouseExited

    private void viewrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordMouseEntered
        Color c1=new Color(16);
        viewrecord.setBackground(c1);
    }//GEN-LAST:event_viewrecordMouseEntered

    private void viewrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordMouseExited
        Color c1=new Color(255,255,255);
        viewrecord.setBackground(c1);
    }//GEN-LAST:event_viewrecordMouseExited

    private void searchrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchrecordActionPerformed
        searchfees a2=new searchfees();
        a2.show();
       
    }//GEN-LAST:event_searchrecordActionPerformed

    private void viewrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrecordActionPerformed
        viewrecord a3=new viewrecord();
        a3.show();
        
    }//GEN-LAST:event_viewrecordActionPerformed

    private void viewcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcourseActionPerformed
       viewcourse a4=new viewcourse();
        a4.show();
        
    }//GEN-LAST:event_viewcourseActionPerformed

    private void editcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcourseActionPerformed
       editcourse b=new editcourse();
        b.show();
       
    }//GEN-LAST:event_editcourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfees;
    private javax.swing.JButton editcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton searchrecord;
    private javax.swing.JButton viewcourse;
    private javax.swing.JButton viewrecord;
    // End of variables declaration//GEN-END:variables
}
